CREATE TABLE client
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name           VARCHAR(64)                             NOT NULL,
    second_name          VARCHAR(64)                             NOT NULL,
    patronymic           VARCHAR(64)                             NOT NULL,
    passport_series      VARCHAR(4)                              NOT NULL,
    passport_number      VARCHAR(6)                              NOT NULL,
    gender               VARCHAR(6)                              NOT NULL,
    marital_status       VARCHAR(7)                              NOT NULL,
    registration_address VARCHAR(255)                            NOT NULL,
    residential_address  VARCHAR(255)                            NOT NULL,
    phone                VARCHAR(16)                             NOT NULL,
    education            VARCHAR(20)                             NOT NULL,
    job                  VARCHAR(255)                            NOT NULL,
    job_title            VARCHAR(255)                            NOT NULL,
    employment_start     date                                    NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE loan_agreement
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status         VARCHAR(10)                             NOT NULL,
    sign_date      date,
    application_id BIGINT,
    CONSTRAINT pk_loanagreement PRIMARY KEY (id)
);

CREATE TABLE loan_application
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status            VARCHAR(10)                             NOT NULL,
    desired_amount    DECIMAL(9, 2)                           NOT NULL,
    approved_amount   DECIMAL(9, 2)                           NOT NULL,
    approved_deadline INTEGER                                 NOT NULL,
    client_id         BIGINT,
    CONSTRAINT pk_loanapplication PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_839e5a6dcef9b22bcdbb40a9a UNIQUE (passport_series, passport_number);

ALTER TABLE loan_agreement
    ADD CONSTRAINT uc_loanagreement_application UNIQUE (application_id);

ALTER TABLE loan_agreement
    ADD CONSTRAINT FK_LOANAGREEMENT_ON_APPLICATION FOREIGN KEY (application_id) REFERENCES loan_application (id);

ALTER TABLE loan_application
    ADD CONSTRAINT FK_LOANAPPLICATION_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);